### PR TITLE
cRIO Build Improvement

### PR DESCRIPTION
**Pull request by emetzlervsi**
I had to make a couple tweaks to get this to build on a 9068 running LV 15. My system was reported as `Linux-3.14.46-rt46-3.5.0f0`.

### CODE REVIEW

**Comment by JackDunaway** [comment]
Looks good to me! The regex improvement seems a more reasonable aim at this
moving target.

Kind regards,

- JRD
Sent via mobile

On Dec 8, 2016, at 10:51 AM, Eric Metzler <notifications@github.com> wrote:

I had to make a couple tweaks to get this to build on a 9068 running LV 15.
My system was reported as Linux-3.14.46-rt46-3.5.0f0.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/featherweight/featherweight/pull/103
Commit Summary

   - added binutils to toolchain install
   - changed regex for Linux RT since mine was '-rt46'

File Changes

   - *M* kernel/CMakeLists.txt
   <https://github.com/featherweight/featherweight/pull/103/files#diff-0>
   (2)
   - *M* kernel/README.md
   <https://github.com/featherweight/featherweight/pull/103/files#diff-1>
   (2)

Patch Links:

   - https://github.com/featherweight/featherweight/pull/103.patch
   - https://github.com/featherweight/featherweight/pull/103.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/featherweight/featherweight/pull/103>, or mute the
thread

**Comment by emetzlervsi** [comment]
Not sure why my commits continue to show up in this pull request. That was not intentional, but I'm not sure how to prevent when there is an open PR.

**Comment by emetzlervsi** [comment]
Realized that I had been testing on a 9031, not a 9068, so still want to test this on ARM.

**Comment by JackDunaway** [comment]
Rebased and merged; thank you, @emetzlervsi ! _(Note that Github may not show this PR as accepted since I rebased after testing on my local dev machine rather than clicking the button from the Web UI)_

**Pull request closed without merging**
